# Mineralogy

This section of the textbook deals largely with crystallography and optical mineralogy. We also revise and expand upon your existing knowledge of the physical properties of minerals. 


## [Physical Properties of Minerals](https://orthospar.github.io/EART2231/mineralogy/physical.html)

:::{.callout-note}
## Learning Outcomes
 - Revise the physical properties of minerals
:::

## [Crystallography](https://orthospar.github.io/EART2231/mineralogy/crystallography.html)

:::{.callout-note}
## Learning Outcomes
 - Understand the definition of a mineral, unit cell and crystal lattice
 - Recognise symmetry elements
 - Classify minerals into one of the 7 crystal systems based on symmetry
 - Predict some physical properties of minerals based on their structure
:::

## [Optical Properties of Minerals](https://orthospar.github.io/EART2231/mineralogy/optical.html)

:::{.callout-note}
## Learning Outcomes
 - Correct use of a petrographic microscope
 - Describe optical properties of minerals in thin section
    - in Plane Polarised Light
    - in Cross Polarised Light
 - Classify (and identify) minerals observed in thin section
:::