# Physical properties of minerals {.unnumbered}
Minerals have a wide range of physical properties that can be diagnostic for the identification of mineral species. We do not expect you to learn all of these properties off by heart for a given set of minerals -- it will come to you in time as you apply and practise your skills as a geologist. What you do need to know is *how* to identify each physical property, so that you can test a sample and look up matching candidates online. Below are the common/main techniques that a geologist is expected to know. We provide a bit more context and detail than what you have covered previously, but we have added plently of links to external resources for further reading.

# Non-destructive Properties I: Just look at it
One of the simplest things we can do to describe the physical properties of a mineral sample is to *just look at it*. The benefit of these techniques is that they are *non-destructive* -- suitable even for museum specimens behind glass cabinets! There are three main properties we can look out for:

## Colour
The colour of a mineral is simple to observe, but the root causes of colour in minerals is usually complicated (not even including how it is detected by the human eye, and subsequently interpreted by the human mind). For some minerals, colour is *diagnostic* -- that is to say that the mineral is that colour and that colour only. Two good examples of this are [:azurite](https://en.wikipedia.org/wiki/Azurite) and [:malachite](https://en.wikipedia.org/wiki/Malachite), which are always blue and green, respectively. The colour of other minerals can vary wildy depending on trace element composition, structural defects or even microscopic inclusions -- [:quartz](https://en.wikipedia.org/wiki/Quartz) is a great example of this, ranging from colourless to yellow to black to purple to pink to green to red ... *and so on*...

#### Further resources:
[Determining Colour and Streak](https://www.mindat.org/a/determining_color_and_streak) by Donald B. Peck on Mindat.org

## Lustre
[:Lustre](https://en.wikipedia.org/wiki/Lustre_(mineralogy)) is the property of *how* a mineral reflects light. It should not be confused with colour, although the two are linked and often described togther. For instance, gold has a metallic lustre and is yellow in colour, whereas copper has a metallic lustre but is orange in colour. Try to avoid using terms that could be confusing... for instance, if you find a mineral that you think looks *silvery*, don't call it "silver", but describe it as "metallic white-grey". Something else to keep in mind is that lustre is very difficult to photograph and display correctly on a computer screen, and depending on the lighting conditions during photography lustre may not be captured at all. Common words to describe lustre include:

- metallic -- highly reflective, looks like metal (e.g., [:pyrite](https://en.wikipedia.org/wiki/Pyrite), [:gold](https://en.wikipedia.org/wiki/Gold), [:copper](https://en.wikipedia.org/wiki/Copper))
- submetallic -- less reflective than metallic, because the mineral is a little bit transluscent (e.g., [:sphalerite](https://en.wikipedia.org/wiki/Sphalerite))
- dull or earthy -- looks like a matte finish, not glossy in any way (e.g., [:kaolinite](https://en.wikipedia.org/wiki/Kaolinite))
- glassy/vitreous -- transparent/transluscent minerals that look like glass (e.g., [:quartz](https://en.wikipedia.org/wiki/Quartz), [:olivine](https://en.wikipedia.org/wiki/Olivine))
- adamantine -- transparent/transluscent minerals that *shine more* than you'd expect, like diamond. They have a high refractive index (e.g., [:cubic zirconia](https://en.wikipedia.org/wiki/Cubic_zirconia))
- resinous -- transparent/transluscent minerals that *shine less* than you'd expect, like plastic or resin (e.g., [:amber](https://en.wikipedia.org/wiki/Amber))  
- pearly -- reflective with a subtle *softness* to it, like a pearl or the inside of a shell (e.g., [:muscovite](https://en.wikipedia.org/wiki/Muscovite))
- greasy -- looks like solid fat or grease (e.g., [:opal](https://en.wikipedia.org/wiki/Opal))
- waxy -- like greasy minerals, but often more opaque or coarser grained than greasy minerals (e.g., [:jadeite](https://en.wikipedia.org/wiki/Jadeite))
- silky - has a sheen like silk due to parallel alignment of microfibres (e.g., [:asbestos](https://en.wikipedia.org/wiki/Asbestos), [:ulexite](https://en.wikipedia.org/wiki/Ulexite))

There are also some other optical effects that are often distinctive, but not lustre *sensu stricto*. These tend to arise due to thin film intereference colours or oriented growth of micro inclusions, and include:

- iridescence/schiller effects -- strong colour play due to micro-scale platy minerals as inclusions or exsolution layers. There are some terms for very specific examples:
    - [:opalescence](https://en.wikipedia.org/wiki/Opalescence) -- lots of splotchy colours, like [:opal](https://en.wikipedia.org/wiki/Opal)
    - [:labradorescence](https://en.wikipedia.org/wiki/Labradorite) -- very commonly displayed in plagioclase
    - [:adularescence](https://en.wikipedia.org/wiki/Adularescence) -- uncommonly (almost rarely) displayed in K-feldspars
    - [:aventurescence](https://en.wikipedia.org/wiki/Aventurescence) -- glittery inclusions in a transparent stone 
- [:chatoyancy](https://en.wikipedia.org/wiki/Chatoyancy) -- usually something silky as parallel micro inclusions in something vitreous
- [:asterisms](https://en.wikipedia.org/wiki/Asterism_(gemology)) -- similar to chatoyancy, but the inclusions are aligned so that a 4- or 6-pointed star is seen. This is more important in gemmology, as the stones need to be cut [:*en cabochon*](https://en.wikipedia.org/wiki/Cabochon) (it's not readily visible in raw/uncut material)

#### Futher Resources:
[Determining Lustre](https://www.mindat.org/article.php/2746/Determining+Lustre%3A+For+Beginning+Collectors) by Donald B. Peck on Mindat.org

## Diaphaneity
Diaphaneity is how light is (or isn't) transmitted through a crystal. Commonly this property is simply termed [:transparency and translucency](https://en.wikipedia.org/wiki/Transparency_and_translucency), but the term also includes the opposite of these -- opacity. Transparent minerals allow light to transmit through them without scattering, i.e., it behaves like glass and you can 'see through it'. Transluscent minerals allow light to transmit through them as well, however there is considerable scattering., i.e., you can see through it a bit, but the image is 'cloudy'. Opaque minerals do not allow light to pass through at all. Minerals may be transparent, transluscent, or opaque, depending on crystal size, presence of inclusions, or minor and trace element contents. 

# Non-destructive Properties II: Close examination
Colour, lustre, and diaphaneity are simple and effective, but are even more useful when combined with knowledge on how minerals grow. 

## Habit
The [:habit](https://en.wikipedia.org/wiki/Crystal_habit) of a mineral describes how it has grown. There are many different terms that can be used to describe growth habits, but a simple place to start is with words used to describe *single* crystals versus words used for *clusters/groups* of minerals. 

### Single Crystals
For single crystals, we describe two separate observations: 1. How well the crystal faces are developed, and 2. the overall 3D shape.

1. In an ideal situation, a mineral will grow with well defined crystal faces that reflect the internal structure of the crystal lattice (more on this in [Crystallography](https://orthospar.github.io/EART2231/mineralogy/crystallography.html)). We have three terms to describe if this has occured in any given sample:
    
 - **Euhedral** -- a single crystal has managed to grow into a perfect representation of its crystal structure and has well developed crystal faces.
 - **Subhedral** -- some crystal faces are well developed, but not all.
 - **Anhedral** -- no crystal faces have developed. 

2. The general shape can also be descibed, and combined with the terms above. This is particularly useful as these terms can start to provide hints on what crystal system the mineral might belong to (again, more on this in [Crystallography](https://orthospar.github.io/EART2231/mineralogy/crystallography.html)). There are many different terms used here, some common/basic use terms include:

 - **Equant** -- more or less the same measurements in all directions
 - **Platy** -- little sheets or plates, very thin in one direction
 - **Acicular** -- little needles, very thin in two directions
 - **Prismatic** -- like a prism (in the geometry sense), longer in one dimension than the other two

### Groups of crystals
How minerals grow togther is another useful property to describe. Some common examples include:

 - **Druse** or **Drusy** -- small crystals growing over the surface of a larger crystal
 - **Massive** or **Compact** -- a large mass of small (<<1 mm) crystals where individual crystal shapes cannot be determined
 - **Botryoidal** -- small grape-like clusters
 - **Colloform** -- a circular or curved/wavy banded habit

## Cleavage/Fracture
Cleavage and Fracture are terms used to describe how the mineral *breaks*. If the mineral repeatedly breaks along a plane, and always in the same orientation(s), then the broken surface is termed a [:**cleavage**](https://en.wikipedia.org/wiki/Cleavage_(crystal)). If the break is planar, but not repeatable, it is termed a *parting*. If the broken surface is irregular and not repeatable (it breaks somewhat randomly in a different direction each time) it is termed a [:**fracture**](https://en.wikipedia.org/wiki/Fracture_(mineralogy)). 

### Cleavage
When describing cleavage, there are two things to look out for: The quality of the cleavage and the number of cleavage planes

  1. The *Quality* of a cleavage describes how easily the mineral breaks along that plane, and is often easily determined by how well the surface reflects light.
      - **Perfect** cleavage often has a highly reflective (i.e., smooth) surface and the mineral will very easily break along this plane. E.g., Muscovite
      - **Good** cleavage will not break as easily as perfect cleavage, and the surface is mostly smooth.
      - **Poor** cleavage is often harder to see, the surface will be more rough than smooth. Sometimes you need to be specifically looking for it to find it. 
      - **Indistinct** cleavage is practically not discernable, but may be noticed as a general tendency for fractures to break in the same direction (usually in thin section under a microscope)
      - **None** refers to no cleavage at all!

  2. The *Number* of cleavages describes how many different cleavage orientations there are (not the number of sheets in a mica crystal, for example). We can use the number of cleavage planes, along with orientation terms to describe how they are related to each other:
      - **1 cleavage plane** is also described as **Basal** cleavage if there is only one orientation in the crystal where cleavage occurs, or **Pinacoidal** if it occurs in combination with a *prismatic* cleavage
      - **2 cleavage planes** are can described as **Prismatic**. The angle between these two planes can be diagnostic (see for example pyroxenes vs amphiboles).
      - **3 cleavage planes** are either described as **Cubic** cleavage if all three planes are perpendicular to each other, or **Rhombohedral** if they are all at some other angle. Galena is an example of *cubic* cleavage, whereas calcite is an example of *rhombohedral* cleavage.
      - **4 cleavage planes** are typically **Octahedral** in orientation. An example of this is fluorite.
      - **6 cleavage planes** is also called **Dodecahedral**. This is typical of sphalerite.

If in doubt, just count the number of cleavages you can see, and describe their orientation to each other as best as possible. 

### Parting
Sometimes a crystallographic plane of weakness might arise due to structural defects in the crystal lattice. However, since this plane of weakness is not necessesarily *repeated* within the crystal structure (such as single twin plane), the crystal will not subsequently always break in the same direction. Importantly, partings may not be present in every crystal, which is why they are not considered a diagnostic feature. However, for minerals that have a solid solution series at high temperature but a solvus 

### Fracture
It is important to note that *all* minerals will have a fracture if broken in a direction that is not aligned with a cleavage orientation. However, fractures are not always easily seen because the minerals cleave so readily! While cleavage has both quality and orientation descriptions, due to the (semi)-random nature of fracture we do not describe the orientation of these breakages. We do still describe the quality of the break, with terms such as:

- **Conchoidal fracture** -- breaking in a curved and concave manner, often looking a little like the curved lines on a sea shell (hence the name, conch-oidal.) Normal glass breaks in this manner.
- **splintery** -- breaks into long thin random splinters
- **hackly** -- a rough breaking surface, like if you snap a piece of metal. 
- **irregular** -- this is what safety glass has been designed to do (so you don't get sharp flakes)

#### Further Resources:
[Determining Fracture and Cleavage](https://www.mindat.org/article.php/2898/Determining+Fracture+and+Cleavage+in+Minerals) by Donald B. Peck on Mindat.org.

## Density
Density can be determined both qualitatively and quantitatively. To determine density qualitatively, one simply needs to 'feel' the weight and use their own judgement to gauge whether or not a mineral is 'light', 'heavy', or 'average'. This requires practice and skill... use the example mineral sets to 'get a feel' for how density varies between minerals. 

Quantitatively, density can be measured and reported as either 'Density' in units of g/cm^3 (that is mass per unit volume), or as 'Specific Gravity' (abbreviated SG) which is the density of a sample divided by the density of water. Numerically these values are more or less equivalent (since the density of water is ~1 g/cm^3) but SG is unitless. 

We do not often need to calculate these values, particularly since SG is only a useful diagnostic in single crystals (and ones large enough to measure properly).

#### Further Resources:
[Determining SG of a mineral](https://www.mindat.org/a/determining_the_specific_gravity_of_a_mineral) by Donald B. Peck on Mindat.org.

# Destructive Properties: The last things to test
Often by this stage, you have identified the mineral with sufficient confidence that you don't need to go any further. Occaisionally, you need further confirmation or to discriminate between candidates with often similar physical properties. 

## Streak
Streak is a modified version of colour. The way light interacts with large single crystals versus a crushed powder of that mineral is distinctly different. Streak is very useful, in that the powdered material almost always has the some colour every time. Note that streak can only be perfomed on a mineral which has a Hardness less than the streak plate (so hard minerals, such as quartz, topaz, beryl, etc, do not produce a good streak). Thankfully, the minerals in which streak is most useful tend to be soft (hardness <5). 

#### Further Resources:
[Determining Colour and Streak](https://www.mindat.org/a/determining_color_and_streak) by Donald B. Peck on Mindat.org

## Hardness
Hardness perhaps better described as 'scratchability'. Hard minerals are not indesctructable, for instance diamond (Moh's Hardness 10) is easily broken with a good whack of a hammer due to its octahedral cleavage, but it can only be 'scratched' by another diamond or something with equal or greater hardness. Like density, Hardness can also be determined quantitatively or qualitatively. There is are specific hardness scales that have SI units ([:Vickers Hardness](https://en.wikipedia.org/wiki/Vickers_hardness_test), [:Knoop Hardness](https://en.wikipedia.org/wiki/Knoop_hardness_test), [:and others](https://en.wikipedia.org/wiki/Hardness_comparison)), but in Geology we like to use the [:Mohs Hardness](https://en.wikipedia.org/wiki/Mohs_scale) scale. It is defined relative to an index of 10 minerals:

1. Talc
2. Gypsum
3. Calcite
4. Fluorite
5. Apatite
6. Orthoclase Feldspar
7. Quartz
8. Topaz
9. Corundum
10. Diamond

These minerals are *defined* to have precicely these hardnesses. Other minerals are equal to these values ONLY IF the index mineral can scratch the test sample and the test sample can scratch the index mineral. If a mineral has a hardness between two of these index minerals, it may be reported as between two values, such as hardness 4-5. Often this is abbreviated to a hardness of 4.5, for example. Note that we do not go further than this -- we would not try to describe something as 4.25 or 4.75.

Qualitatively, your fingernail has a Moh's hardness of '2.5', so if you can scratch it with your fingernail it is 'soft'. You may have a quartz (Mohs 7) point on you for testing mineral hardness, at which point if you cannot scratch your unknown sample with quartz it is 'hard'. If you are using a scribe with a tungsten-carbide tip, it will scratch just about everything but one can get a feel for how much effort is required to get a 'good scratch'.

#### Further Resources:
[Determining Hardness](https://www.mindat.org/a/determining_the_hardness_of_a_mineral) by Donald B. Peck on Mindat.org

# Special Properties: Niche, but useful
Some properties are highly distinctive when they are observed in a sample, but are either rare in most minerals (and so not worth testing all the time) or require particular equipment to test. 

## Magnetism
Magnetism is a great case of a simple and effective test, but for most minerals the test will prove negative. The main magnetic minerals to look out for are magnetite and pyrrhotite, which can often be confused with hematite or pyrite, respectively. 

## Fluorescence
Some minerals [:fluorescence](https://en.wikipedia.org/wiki/Fluorescence) under UV light, and the fluorescence colour can be diagnostic for certain minerals. For instance, both eucryptite and scheelite can be found associated with quartz. It is very difficult to tell these minerals apart as they are all often colourless-white, vitreous crystals with chonchoidal fracture. However, eucryptite has a distinctive bright red short wave UV response, and sheelite has a very bright blue short wave UV response, while quartz is unresponsive to UV illumination. As fluorescence is a property that requires a UV-light source (which is dangerous to stare into,or if you leave your hands under it), it is not routinely used unless there is a specific need for it (such as exploration for W in the case of scheelite).

