# Microscope Setup and Use Reminders {.unnumbered}

:::{.callout-important}
## First time set-up
 Do not touch the microscopes until you have been intially instructed on their use. 
:::

We will demonstrate the correct way to handle and set-up the microscopes during the first laboratory session in which we will use them. Remember that these are a shared resource with your colleagues and each microscope will have multiple regular users throughout the semester. It is in your interest, as a community, to make sure the microscopes are properly looked after. 


## Correct Use of Microscopes

### At the start of a session

- Carefully place the microscope on the bench, directly in front of you, and not placed too far back on the bench.

:::{.callout-tip}
## Do: Always use two hands!
Always use two hands when picking up and moving the microscope -- one hand on the neck at the back of the microscope, and one hand underneath the base.
:::
:::{.callout-important}
## Don't: Grab the microcope by the head!
The head, stage and turrent of the microscope are not always secure, and are not designed to bear the full weight of the microscope. 
:::

- Plug in the power supply box. Make sure the dial is set to low voltage, and then turn it on. Slowly turn up the voltage to sufficient illumination.

:::{.callout-caution}
## Halogen bulbs
The light source is a halogen bulb, which is a kind of incandescent light source. As such, bulbs can 'blow' with sudden changes in voltage and temperature. Slowly turning up the voltage improves their life span... and makes it much less likely to blow during an exam!
:::

Before you place a slide on the stage, using the lowest power magnification, check the following:

- Under PPL check that the light is uniform with no shadows or obstructions. 
- Under XPL, check that the view is black. Not just a bit grey, and definitely not pink/purple!

### During a session

- Always start at the lowest magnification
- Change to higher magnifications by holding the **rim of the turret**, not via the objective lenses.
- Change through the higher magnification lenses in order, and focus each lens before moving to the next
- Pay close attention to the working distance at each magnification, make sure you do not focus the objective lens **into** the slide.

:::{.callout-important}
## Focusing at high magnification
Only use the fine focus control, particularly with 40x objective lenses or higher. The coarse focus will move the stage too much, and you risk pushing the objective lens *through* the stage, breaking the slide and damaging the lens.
:::

- Always switch back to the lowest power objective before removing or changing slides.

- Only work on one slide at a time, and return the slide to the correct tray or drawer immediately when finished. 

:::{.callout-important}
## Never leave the slide on the stage
Even if you are only walking away for a few minutes, put the slide away (and turn off the power and put the cover on the microscope). Leaving slides on the microsope stage makes them unavailable to other students, and risks lose and/or damage to the slides if the microscope is packed up accidentally with the side still on the stage.
:::

### At the end of a session

- Set the objective lens to the lowest magnification
- Remove the slide, and store it where it belongs.
- Turn down the voltage on the power supply unit, then turn it off. 
- Place the dust cover back on top of the microscope.
- Carefully, using two hands, return the microscope to the cupboard.

## General Care

- Operate moving parts gently (such as the stage, turret, analyser, diaphram, etc) and take care not to bump the microscope.
- Do not touch the lens surfaces, and never attempt to clean them (they can be scratched easily). If you suspect your microscope needs care and maintainence, let your instructor know and we can arrange to have it cleaned. 
- Wash your hands before using the microscope! Not only is this important for the management of repiratory illnesses such as COVID-19, but this helps to keep the microscopes clean and grime free. 
- Do not eat or drink at your desk with the microscope out! Water is the only exception. If you want to have a coffee, or an energy drink, walk away from your desk and take 5-10 mins. This is also good for your eyes and posture.
- If you are not actively using your microscope, turn it OFF and put the cover on! Dust is a menace and gets in there even if you are only gone for 10 mins. 